name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe  # Replace with the username and repository name you want to checkout
          ref: main  # Replace with the branch or tag you want to checkout
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build

      - name: Load SSH key and deploy to GitHub Pages
        run: |
          npm install -g gh-pages

          # Enable verbose mode for ssh-add
          echo "Adding SSH key to the agent with verbose output..."
          eval "$(ssh-agent -s)"
          ssh-add -v <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')

          # Display the loaded keys
          echo "List of loaded keys:"
          ssh-add -L

          # Configure Git user
          git config --global user.email "fergus586@gmail.com"
          git config --global user.name "fergus586"

          # Create a CNAME file with the custom domain
          echo "bloxe.art" > ./build/CNAME

          # Deploy to GitHub Pages
          echo "Deploying to GitHub Pages with custom domain (bloxe.art)..."
          gh-pages -d ./build -r git@github.com:fergus586/bloxe.git -b gh-pages --add
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY2 }}
