name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe
          ref: main
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          # You can conditionally set CI to false here if needed
          export CI=false

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Pages Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          name: pages-artifact

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id-token-request-url: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
          artifact_name: pages-artifact
