name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe  # Replace with the username and repository name you want to checkout
          ref: main  # Replace with the branch or tag you want to checkout

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Load SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          eval $(ssh-agent -s)
          ssh-add deploy_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d ./build -r https://github.com/fergus586/bloxe.git -b main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
