name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - main # Adjust this to your main branch
  # Add other events or conditions if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe
          ref: main # Specify the branch you want to build

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Adjust to match your main branch
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # Specify the branch to deploy to
          folder: ./build # Adjust to the path where your build artifacts are
