name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe  # Replace with the username and repository name you want to checkout
          ref: main  # Replace with the branch or tag you want to checkout

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
