name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe
          ref: main
          ssh-key: ${{ secrets.BLOXEART_DEPLOY_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d ./build -r git@github.com:fergus586/bloxe.git -b gh-pages
