name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe  # Replace with the username and repository name you want to checkout
          ref: main  # Replace with the branch or tag you want to checkout
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}  # Updated to use DEPLOY_SSH_KEY secret

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "fergus586@gmail.com"
          git config --global user.name "fergus586"
          git remote add origin_with_token https://${{ secrets.GITHUB_TOKEN }}@github.com/BloxeArt/bloxe.git
          git subtree split --prefix build -b gh-pages
          git push origin_with_token gh-pages:gh-pages --force

