name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from another repository
        uses: actions/checkout@v2
        with:
          repository: BloxeArt/bloxe
          ref: main
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install react-ga
        run: npm install react-ga

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Load SSH key and deploy to GitHub Pages
        run: |
          npm install -g gh-pages

          # Start the SSH agent
          eval "$(ssh-agent -s)"

          # Add the SSH private key to the agent
          ssh-add - <<< "$SSH_PRIVATE_KEY"

          # Configure Git user
          git config --global user.email "fergus586@gmail.com"
          git config --global user.name "fergus586"

          # Create a CNAME file with the custom domain
          echo "bloxe.art" > ./build/CNAME

          # Deploy to GitHub Pages
          gh-pages -d ./build -r git@github.com:fergus586/bloxe.git -b gh-pages --add
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY2 }}
