name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          with:
            repository: BloxeArt/bloxe
            ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
          with:
            node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            folder: ./build
            permissions:
              id-token: write
